import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';

const alternativesMap = {
  'allroundautomations-plsqldeveloper': 'DBeaver / DataGrip',
  'almico-speedfan': 'lm-sensors / Fancontrol',
  'alphayama-poweriast': 'Native Linux Compose Key / Fcitx',
  'altdrag-altdrag': 'Natively supported in Linux (Alt + Drag is built-in)',
  'altsnap-altsnap': 'Natively supported in Linux (Alt + Drag is built-in)',
  'altap-salamander': 'Double Commander / Krusader / Dolphin',
  'amanharwara-altus': 'Native Linux Version|github:amanharwara/altus',
  'amazon-awscli': 'Native Linux Version',
  'amazon-awsvpnclient': 'OpenVPN / WireGuard / NetworkManager',
  'amazon-chime': 'Native Linux Version (Web Client / PWA)',
  'amazon-corretto-11': 'Native Linux Version',
  'amazon-corretto-17': 'Native Linux Version',
  'amazon-corretto-18': 'Native Linux Version',
  'amazon-corretto-19': 'Native Linux Version',
  'amazon-corretto-8': 'Native Linux Version',
  'amazon-games': 'Heroic Games Launcher / Lutris',
  'anki-anki': 'Native Linux Version|flathub:net.ankiweb.Anki',
  'antsoftware-antrenamer': 'KRename / Métamorphose / Bulk Rename (Thunar)',
  'anthonybeaumont-achievementwatcher': 'Native Linux Version',
  'antimicro-antimicro': 'Native Linux Version|github:jasonwryan/antimicro',
  'antimicrox-antimicroxportable': 'Native Linux Version|flathub:io.github.antimicrox.antimicrox',
  'antibodysoftware-bulkimagedownloader': 'DownThemAll! / gallery-dl / wget',
  'antibodysoftware-wizfile': 'FSearch / Catfish / locate',
  'antibodysoftware-wizkey': 'Native Linux Compose Key',
  'antibodysoftware-wizmouse': 'Natively supported in Linux (Scroll under cursor is default)',
  'antibodysoftware-wiztree': 'QDirStat / Baobab (Disk Usage Analyzer) / NCurses Disk Usage (ncdu)',
  'antoineaflalo-soundswitch': 'Natively supported in KDE/GNOME or extensions',
  'antonikepinski-parsifydesktop': 'Native Linux Version|github:antonikepinski/parsify-desktop',
  'antonycourtney-tad': 'Native Linux Version|github:antonycourtney/tad',
  'antutu-antutubenchmark': 'Geekbench / Phoronix Test Suite',
  'anydesksoftwaregmbh-anydesk': 'Native Linux Version',
  'anylogic-anylogic-personal': 'Native Linux Version',
  'anylogic-anylogic-professional': 'Native Linux Version',
  'anylogic-anylogic-university': 'Native Linux Version',
  'anytxt-anytxtsearcher': 'Recoll / fzf / ripgrep',
  'anydo-anydo': 'Native Linux Version (Web Client / PWA)',
  'apache-directorystudio': 'Native Linux Version',
  'apache-groovy-2-5': 'Native Linux Version',
  'apache-groovy-3': 'Native Linux Version',
  'apache-groovy-4': 'Native Linux Version',
  'apache-openoffice': 'LibreOffice / ONLYOFFICE',
  'apachefriends-xampp-7-4': 'Native Linux Version',
  'apachefriends-xampp-8-0': 'Native Linux Version',
  'apachefriends-xampp-8-1': 'Native Linux Version',
  'apachefriends-xampp-8-2': 'Native Linux Version',
  'appwork-jdownloader': 'Native Linux Version',
  'appbytroye-koodoreader': 'Native Linux Version|flathub:com.github.troyeguo.koodo-reader',
  'apple-dvdorcdsharing': 'Natively supported in Linux network sharing',
  'apple-windowsmigrationassistant': 'Deja Dup / manual rsync',
  'approximatrix-simplyfortran': 'Code::Blocks / Eclipse / VS Code with Fortran plugin',
  'apreltech-hvmanager': 'WebVirtMgr / Cockpit / Kimchi',
  'apreltech-powermanager': 'Natively supported in Linux (TLP / power-profiles-daemon)',
  'apreltech-silentinstallbuilder': 'Ansible / SaltStack / Puppet',
  'apreltech-silentinstallbuilder-beta': 'Ansible / SaltStack / Puppet',
  'arcaderenegade-sidebardiagnostics': 'Conky / GKrellM / MangoHud',
  'arduinosa-ide-beta': 'Native Linux Version|flathub:cc.arduino.IDE2',
  'arduinosa-ide-rc': 'Native Linux Version|flathub:cc.arduino.IDE2',
  'argotronic-argusmonitor': 'lm-sensors / Fancontrol / Liquidctl',
  'aries-sciences-llc-ai-chess': 'Native Linux Version',
  'arm-gnuarmembeddedtoolchain': 'Native Linux Version',
  'armcord-armcord': 'Native Linux Version|flathub:xyz.armcord.ArmCord',
  'armin2208-windowsautonightmode': 'Natively supported in GNOME / KDE / Night Light',
  'arobasmusic-guitarpro-7': 'TuxGuitar / MuseScore',
  'artifexsoftware-ghostscript': 'Native Linux Version',
  'artisteerlimited-nicepage': 'Mobirise (via Wine) / WordPress / Webflow (Web)',
  'asana-asana': 'Native Linux Version (Web Client / PWA)',
  'ascension-ascensionlauncher': 'Native Linux Version (via Wine/Lutris)',
  'ashishbharadwajj-flawesome': 'Native Linux Version|github:ashishbharadwajj/flawesome',
  'ashleystone-defaultaudio': 'Natively supported in Linux (PulseAudio / PipeWire control)',
  'ashleystone-sitdownmw': 'Natively supported (nice / renice commands)',
  'asiasoftonline-playparkdownloader': 'Steam / Lutris',
  'astrocomma-astrogrep': 'KFind / Catfish / ripgrep',
  'astronomer-astro': 'Native Linux Version',
  'asus-armourycrate': 'OpenRGB / OpenAsusConfigurator / asusctl',
  'atlassian-sourcetree': 'GitKraken / Gitg / lazygit / Sublime Merge',
  'atola-findandmount': 'TestDisk / GParted',
  'atomixproductions-virtualdj': 'Mixxx',
  'atrix-atrixlauncher': 'Bottles / Lutris',
  'atticus64-juice': 'Oh My Zsh / Starship / Fish',
  'audient-evo': 'Natively class-compliant (PulseAudio / PipeWire / ALSA)',
  'audient-sono': 'Natively class-compliant (PulseAudio / PipeWire / ALSA)',
  'audiorangerit-audioranger': 'MusicBrainz Picard / Kid3',
  'audius-audius': 'Native Linux Version (Web Client / PWA)',
  'auraside-mantle': 'Native Linux Version (Minecraft mods)',
  'auslogics-diskdefrag': 'Not needed in Linux (Ext4/F2FS/Btrfs don\'t require defragging)',
  'austinleath-r6rc': 'Native Linux Version (Web / PWA)',
  'autohotkey-autohotkey': 'Autokey / Espanso / KMonad',
  'autoit-autoit': 'Autokey / xdotool',
  'autodesk-desktopapp': 'Not needed on Linux',
  'autodesk-eagle': 'Native Linux Version',
  'automatedlab-automatedlab': 'Terraform / Vagrant / Ansible',
  'autonomoussoftware-metronomewallet': 'Native Linux Version',
  'aveeksaha-duskplayer': 'Native Linux Version|github:aveeksaha/duskplayer',
  'avisynth-avisynth': 'VapourSynth',
  'avisynth-avisynthplus': 'VapourSynth',
  'avidemux-avidemux': 'Native Linux Version|flathub:org.avidemux.Avidemux',
  'avocode-avocode': 'Native Linux Version (Web / Figma)',
  'avogadro-avogadro': 'Native Linux Version|flathub:org.openchemistry.Avogadro2',
  'awthwathje-steascree': 'Native Linux Version|github:awthwathje/steascree',
  'axcrypt-axcrypt': 'Cryptomator / VeraCrypt / GnuPG',
  'axiscommunications-axiscamerastation': 'ZoneMinder / Shinobi / Kerberos.io',
  'axure-axurerp-10': 'Penpot / Figma / Pencil Project',
  'ayibatariibaba-stopawu': 'Not needed in Linux',
  'azul-zulu-11-jdk': 'Native Linux Version',
  'azul-zulu-11-jre': 'Native Linux Version',
  'azul-zulu-13-jdk': 'Native Linux Version',
  'azul-zulu-13-jre': 'Native Linux Version',
  'azul-zulu-15-jdk': 'Native Linux Version',
  'azul-zulu-15-jre': 'Native Linux Version',
  'azul-zulu-16-jdk': 'Native Linux Version',
  'azul-zulu-16-jre': 'Native Linux Version',
  'azul-zulu-17-jdk': 'Native Linux Version',
  'azul-zulu-17-jre': 'Native Linux Version',
  'azul-zulu-18-jdk': 'Native Linux Version',
  'azul-zulu-18-jre': 'Native Linux Version',
  'azul-zulu-19-jdk': 'Native Linux Version',
  'azul-zulu-6-jdk': 'Native Linux Version',
  'azul-zulu-7-jdk': 'Native Linux Version',
  'azul-zulu-7-jre': 'Native Linux Version',
  'azul-zulu-8-jdk': 'Native Linux Version',
  'azul-zulu-8-jre': 'Native Linux Version',
  'azul-zulu-9-jdk': 'Native Linux Version',
  'azul-zulu-9-jre': 'Native Linux Version',
  'azul-zulufx-17-jdk': 'Native Linux Version',
  'azul-zulufx-18-jdk': 'Native Linux Version',
  'azul-zulufx-19-jdk': 'Native Linux Version',
  'acaudwell-gource': 'Native Linux Version|flathub:ca.gource.Gource',
  'acrosync-duplicacyweb': 'Native Linux Version',
  'advancedfx-hlae': 'Runs under Wine',
  'afractal-twittertron': 'Cawbird / Web Client',
  'ahkohd-switch': 'Native Linux Version',
  'ahmetb-kubectx': 'Native Linux Version|github:ahmetb/kubectx',
  'ahmetb-kubens': 'Native Linux Version|github:ahmetb/kubectx',
  'ajeetdsouza-zoxide': 'Native Linux Version|github:ajeetdsouza/zoxide',
  'akeo-ie-zadig': 'Not needed (Linux handles USB drivers natively)',
  'alagrede-znote': 'Native Linux Version|github:alagrede/znote',
  'alesimula-wsa_pacman': 'Waydroid / Anbox',
  'alexkim205-g-desktop-suite': 'Native Linux Version (Web Client / PWA)',
  'alexx2000-doublecommander': 'Native Linux Version|flathub:com.doublecmd.DoubleCommander',
  'ali50m-addcurrentpath': 'Natively supported (export PATH in .bashrc/.zshrc)',
  'aliceandbob-io-aliceandbob': 'Native Linux Version (Web / PWA)',
  'altair-graphql-altair': 'Native Linux Version|flathub:com.altairhtml.AltairGraphQLClient',
  'aluxnimm-outlookcaldavsynchronizer': 'Natively supported in Evolution / KMail / Thunderbird',
  'amitmerchant1990-electron-markdownify': 'Native Linux Version|github:amitmerchant1990/electron-markdownify',
  'andrewbrey-flot': 'Native Linux Version (Web / PWA)',
  'androidwg-corkscrew': 'Native Linux Version',
  'angryziber-angryipscanner': 'Native Linux Version|flathub:org.angryziber.ipscan',
  'ankurk91-googlechatelectron': 'Native Linux Version|github:ankurk91/google-chat-electron',
  'antonreshetov-masscode': 'Native Linux Version|flathub:io.github.antonreshetov.masscode',
  'arcusmaximus-ytsubconverter': 'Native Linux Version (via Wine)',
};

const dbDir = '.wrangler/state/v3/d1/miniflare-D1DatabaseObject/';
const files = fs.readdirSync(dbDir).filter(f => f.endsWith('.sqlite') && f !== 'metadata.sqlite');

if (files.length === 0) {
  console.error('No SQLite database found.');
  process.exit(1);
}

const dbPath = path.join(dbDir, files[0]);
const db = new Database(dbPath);

const stmt = db.prepare('UPDATE apps SET linux_alternative = ? WHERE id = ?');

let updatedCount = 0;
const transaction = db.transaction((data) => {
  for (const [id, alt] of Object.entries(data)) {
    const info = stmt.run(alt, id);
    if (info.changes > 0) {
      updatedCount++;
    }
  }
});

transaction(alternativesMap);

console.log(`Successfully updated ${updatedCount} apps with their Linux alternatives locally!`);
db.close();
